### PR TITLE
Fix Split function with 0 erasure

### LINKED ISSUE #232: panic: runtime error: index out of range at Split()
Thank you for the great library!

I have a crash when use the Split() function, below is the details:

**Version**: main
**Steps to reproduce**

```
func main() {
    data := make([]byte, 512)
    var ecctest reedsolomon.Encoder
    ecctest, _ = reedsolomon.New(1, 0)
    _, _ = ecctest.Split(data)
}
```

**Log**
```

panic: runtime error: index out of range [512] with length 512

goroutine 1 [running]:
github.com/klauspost/reedsolomon.(*reedSolomon).Split(0x1?, {0xc0000a6000, 0x0?, 0x0?})
```

I have read the code, and find the issues may from this code:

https://github.com/klauspost/reedsolomon/blob/b413df32aec2953ebc9e85167dc4b4969be4a3a6/reedsolomon.go#L1564

When `len(data) == (r.totalShards * perShard)` it will go to line 1577, and try to set `data[512]` as `0` which will cause index out of range. It seems no need to do if `len(data) == (r.totalShards * perShard)` ?

Thanks!

### PR DESCRIPTION
**Pull request by klauspost**
Fixes #232

### CODE REVIEW

File: reedsolomon.go [hunk 1]
```diff
@@ -1551,6 +1551,10 @@ func (r *reedSolomon) Split(data []byte) ([][]byte, error) {
 	if len(data) == 0 {
 		return nil, ErrShortData
 	}
+	if r.totalShards == 1 {
+		return [][]byte{data}, nil
+	}
```
Comment (cleotiswooten404-lgtm) [inline reedsolomon.go:1556]: 5b4e063615df032398251bcce6c665ddc7308734
```suggestion
	### }Fixes #335 

[Scanned_20260430_211733.pdf](https://github.com/user-attachments/files/27379860/Scanned_20260430_211733.pdf)

```

Comment (klauspost) [reply reedsolomon.go:1556]: @cleotiswooten404-lgtm Please stop disturbing people with pointless comments. Next post will be reported.
